<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 错误

      // 1
      // 一些基本概念
      // - 1. 所有抛出的错误，都是 Error 对象的实例

      // 2
      // Error 构造函数
      // - 参数：表示错误提示
      // - 实例属性
      //  - err.message：错误提示信息
      //  - err.name：错误名称（非标准属性）
      //  - err.stack：错误堆栈（非标准属性）

      // 3
      // 错误对象的类型 ( 8种 ) - 6种错误对象 + 1种原生错误对象 + 1种自定义错误对象
      // - 6种错误对象
      //  - ReferenceError ----- 引用出错，比如 - 引用不存在的变量
      //  - RangeError --------- 变量范围错误
      //  - SyntaxError -------- 语法错误
      //  - TypeError ---------- 类型错误，变量不是预期类型
      //  - URIError ----------- URI相关函数报错
      //  - EvalError ---------- eval函数没有被正确执行
      // - 1种自定义对象
      //  - 自定义对象其实就是利用了 ( 原型链式继承 - 继承了 new Error() 的实例 )

      // 4
      // - 扩展：如何手动中断 js 执行 ？
      // - 回答：throw
      // - throw
      //  - 作用：语句可以中断程序执行，并抛出一个错误
      //  - 特点：throw可以抛出任何值

      // --------------
      // xxx
      // 原生错误 和 自定义错误
      const err = new Error(
        "Error构造函数接收一个参数，该参数表示 ( 错误提示 )"
      );
      function CustomError(message) {
        this.message = message;
      }
      CustomError.prototype = err;
      CustomError.prototype.constructor = CustomError;
      const customError = new CustomError(
        "自定义错误的错误提示 - 自定义错误其实就是利用了原型链式继承"
      );
    </script>
  </body>
</html>
